language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0

services:
  - memcached

install: composer install --dev

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

notifications:
  email: false
  slack:
    secure: ElO306IhEWfaIBAVNzNcOfa9nHAKeCzDAeLJABSgWO9iuscJAV+zOelkPoCkiMQ4FAvdEZiPh9/fmCKxhmlEo+HVsjVKhPdd+17d2tvNV1+MNWsKorPJQX50pvdIBcVqYuC0spNzNUXaRqFkI//bVzi48Ry4H2fY3yLFUIBcZmw=
